### ISSUE TITLE
[茶话会][2024-10-27][20 分钟] 基本乐理之一眼顶针五线谱

### ISSUE THREAD

**Issue by IceWind233** [io-club/share#13]
### 作者

IceWind233

### 内容类型

- [ ] 技术类
- [X] 其他

### 摘要/大纲

# 乐理基础
识谱 能看懂五线谱就是winwin

### 关闭 Issue 前请先确认以下内容

- [x] PPT 是否上传：<#18>
- [x] 视频是否上传：<https://www.bilibili.com/video/BV12D1uYfEe7>

**Comment by trdthg** [comment]
good
