### ISSUE TITLE
[茶话会][2024.11.24][30分钟] PR入门-视频剪辑

### ISSUE THREAD

**Issue by Batacooooo** [io-club/share#29]
### 作者

云天

### 内容类型

- [ ] 技术类
- [X] 其他

### 摘要/大纲

#PR入门-视频剪辑
---
### 1.软件安装以及打开
放一个[网站](https://www.yuque.com/u34127441/ki1gww/dmamv4r7u3fz65lc?singleDoc#)
建议下载***2021***或***2024***

### 2.创作一个视频的流程
- 创建项目
- 导入素材
- 工作内容
- 导出视频
> 不涉及过于繁杂的名词解释,目标为了解视频制作的大致内容以及最终导出视频

### 3.简单效果的制作(可能选择一个来讲
- 通过动态拼贴在PR做拉镜效果
> 为什么是pr?  因为ae俺还不咋会用=.=
- 抽帧效果
> 类似败犬女主ed1 ( love2000 )

~~*或者是其他的效果让我想想,俺也不会太多*~~

### 补充说明

ae在学了...先挖个坑(?
ppt还在想怎么搞, 目前想的是后续把上面摘要完善一下, 然后大部分直接在pr里操作吧==

### 关闭 Issue 前请先确认以下内容

- [x] PPT 是否上传：<https://github.com/io-club/share/commit/a1b11a2923799bb2aabf3f4c9e2af54c3bfca62b>
- [x] 视频是否上传：<https://www.bilibili.com/video/BV19zB8YGExq>

**Comment by trdthg** [comment]
Github 标题可以编辑，能否把 2024.11.10 修改为预期的时间？
