### ISSUE TITLE
[需求] 创建茶话会参加模板

### ISSUE THREAD

**Issue by trdthg** [io-club/share#5]
## 如何认领

请直接在下方回复，我会把 issue 的 assignees 设置为你

## 需求

创建 issue 时要求参加者必须填写以下内容(暂定)

- 作者: 昵称/github_id/xxx
- 内容形式：可以是复选框，课程/报告/xxx/其他
- 内容标题
- 摘要: 可选
- 预计时长
- 参加时间

关闭 issue 前需要检查

- PPT 是否上传：需要关联到 pr 链接
- 如果有源文件例如 markdown 文件 需要上传文件 [可选?]
- 视频是否上传: 是需要链接，否不用填

## 实现方式

Github 支持在 `.github/` 文件夹下创建一个模板文件规定 issue 的格式

## 文档资料

- github 文档: https://docs.github.com/zh/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

## 难度

简单 (0 基础现学现做级别)

## 能力要求

- 需要能够正常访问 github，并注册账号
- 了解 yaml 文件格式
- 了解 github issue 使用方法
- 能够自学上面的文档

## 成果验收

相关链接: <仓库/PR 链接等>
截图展示: <图片>

## 评价

<待任务结束填写>

**Comment by shan-yicun** [comment]
Here,me! That's the io member.

**Comment by trdthg** [comment]
@shan-yicun any progress?

**Comment by trdthg** [comment]
记录一下设想的其他模块

- io 相关开发任务发布
- 比赛信息发布/组队征集/比赛进度跟踪
- 其他内容...
