### ISSUE TITLE
[任务] 茶话会 issue 报名事件自动同步到 QQ 

### ISSUE THREAD

**Issue by trdthg** [io-club/share#6]
## 如何认领

请直接在下方回复，我会把 issue 的 assignees 设置为你

## 需求

当有人创建 issue 报名时，自动将报名信息同步到 qq 群聊

## 实现方式

用户创建 issue，自动触发 github webhook 发送 post 请求; 这一步需要: 

- 在 github 设置配置 webhook url 等内容

后端收到请求并处理; 这一步需要:	

- 解析 issue 内容, 提取出作者，标题等信息

转发到 qq 群; 这一步需要:

- 调用 qq 机器人发送消息

## 文档资料

- github webhook: https://docs.github.com/zh/webhooks
- onebot（统一的聊天机器人应用接口标准）: https://onebot.dev/
- napcat(qq 的 onebot 实现): https://napneko.com/
- nonebot(python 机器人框架): https://nonebot.dev/docs/quick-start
- fastapi(仅举例，似乎是 nonebot 默认推荐的框架): https://fastapi.tiangolo.com/zh/tutorial/first-steps/

## 难度

中等 (需要学习一定知识，但是功能体量不大，稍有挑战)

## 能力要求

- 需要能够正常访问 github，并注册账号
- 知道 webhook 的概念
- 了解后端(例如 fastapi)基础使用方法
- 对编写 qq 机器人感兴趣

## 关闭 Issue 前请确认以下内容

- [x] 代码已经上传：<https://github.com/io-club/IOGAS-QQ>
- [x] 准备参加茶话会分享：<https://github.com/io-club/share/issues/19>

**Comment by heky12356** [comment]
能做，但是没有第二第三项能力，可以学，但是时间慢，只有周六日有大量时间，平时只能拿出1h来写，可能会摸。
加分项：熟练使用chatgpt和搜索引擎，有部署过qq框架，熟悉linux基本操作

**Comment by trdthg** [comment]
ok，先给你了，每周在这里回复同步一次进度

**Comment by heky12356** [comment]
用go写后端，已经实现了当github发起issue的时候后端可以接受到信息，尚未和qq机器人对接

**Comment by heky12356** [comment]
实现了提取issue中body的信息并通过onebot的api向qq群中转发

**Comment by heky12356** [comment]
基本实现内容
![image](https://github.com/user-attachments/assets/217b7d63-3109-46eb-a945-44cd95532538)

**Comment by heky12356** [comment]
![image](https://github.com/user-attachments/assets/f6894a56-a3b8-4aa6-af5e-9816cd461ce4)
xia上图为链接bug修改后。

现在需解决：1设置为精华消息，2，发布群公告

**Comment by heky12356** [comment]
目前主要文件已上传仓库
https://github.com/heky12356/synctoqq

**Comment by trdthg** [comment]
很好，进度很快👍

> 目前主要文件已上传仓库

我大致看了一下，感觉很不错，不过有一个地方不太理解

https://github.com/heky12356/synctoqq/blob/021d6c0b7b005d6441551e05b1dec3c0bcf0b59c/main.go#L135

这里为什么还要保持连接 10s？

> 现在需解决：1设置为精华消息，2，发布群公告

[onebot 标准](https://12.onebot.dev/interface/message/actions/) 里似乎没有定义上面两个功能的 api

请问是否有可能的实现方案?

**Comment by heky12356** [comment]
因为我现在使用的机器人napcat实现了go-cqhttp的大部分 API。go-cqhttp中有设置精华消息和发送群公告的api，我打算从这里着手，修改原来的发送函数，让他获取消息的id，然后利用go-cqhttp中的api来实现这两个功能。
保持连接10秒是为了保证消息确实发送了，因为原本不需要读取响应，所以通过这种方式来完成，不过之后的版本应该会读取响应来判断

**Comment by trdthg** [comment]
> 因为我现在使用的机器人napcat实现了go-cqhttp的大部分 API。go-cqhttp中有设置精华消息和发送群公告的api

看到了，https://napneko.com/develop/api#go-cqhttp-api 这两个接口都支持了

> 不过之后的版本应该会读取响应来判断

good

**Comment by heky12356** [comment]
两个功能基本完成，现在的还有一点收尾就是判断一下issue的action，只有当其是open的时候才发送消息

**Comment by heky12356** [comment]
完成了，代码一会儿上传，之后编译一个linux版本然后写一个README就ok了

**Comment by heky12356** [comment]
![image](https://github.com/user-attachments/assets/02913d8b-8900-41ac-ba3b-e335ec476f8b)

**Comment by trdthg** [comment]
对了，请问一下，github webhooks 返回的 issue "内容" 是一段纯文本吗
假如我以 mardown 格式编写，是不是原来的 `#` 也都会保留？

**Comment by heky12356** [comment]
返回的是纯文本，假如是用md格式编写，可能应该要对其进行一些操作，不过，话说qq支持md吗？理论上如果qq支持md，那么输出的是md文件，qq应该会自己识别，如果不支持，那么就算我在后端修改那么也找不到qq支持的格式。

**Comment by heky12356** [comment]
> 输出的是md文件
文本，这里打错了

**Comment by heky12356** [comment]
经测试，不支持

**Comment by trdthg** [comment]
- 写个 README 教一下
  - 纯净 ubuntu 如何安装项目依赖，编译，运行
  - 如何配置 qq 机器人
  - 配置文件的模板 (把敏感信息，用户需要填的信息 换成文字说明)
- 删除仓库 exe 二进制等
- 由于 qq 群聊不支持 markdown，我们需要按照 issue 内容做一些信息提取工作。
  - 目前可以只提取茶话会相关的 issue 发送
  - 我有一些提取思路，你可以作为参考
    - 标题目前定为 `[分类] [其他可能信息]*: 标题` 的形式
    - github issue 模板转成的内容默认使用的大标题是 `###`

**Comment by heky12356** [comment]
![image](https://github.com/user-attachments/assets/1b77ef3e-97ef-4f3c-84e1-94b9900baf1a)
![image](https://github.com/user-attachments/assets/229d7e5e-90f5-4df3-b752-a1b32cb55502)
我将茶话会的模板进行匹配目前可以达到上面的效果
之后的努力方向：使用正则来匹配title，区分出茶话会以及任务。
如果是茶话会就按照上面的模板发，如果是任务就单独发一个github的链接

**Comment by heky12356** [comment]
上面的 无 是读取为“_No response_”时显示
正式版中如果是 无 就不换行，不是 无 就换行
例如
```bash
摘要/大纲：
好多测试啊
补充说明：无
```

补充说明：在代码中关于 无 的判断 也就是对“_No response_” （发布时没有填写任何内容）的判断只有是  补充说明  部分才有，因为在逻辑上 摘要/大纲 的部分不可能为无，所以为了使代码更加简洁在 摘要/大纲 部分没有这部分的判断

**Comment by heky12356** [comment]
![image](https://github.com/user-attachments/assets/d017999c-593c-4995-a6a0-f7fc44992216)
![image](https://github.com/user-attachments/assets/a5d209c0-cc94-4794-baa9-6741c8d6dc49)
基本实现需求，如上图所示

**Comment by heky12356** [comment]
目前待完成：
1. 构建Makefile文件，或者打包为linux可执行文件
2. 编写README

其他：由于编写环境为windows所以实际的linux测试环节尚未进行，仍需一定的调试

**Comment by heky12356** [comment]
之后方向对于茶话会或者任务的特殊操作，例如，当任务认领时（assign）的提示，以及当茶话会上传课件（issue的close）的提示

**Comment by heky12356** [comment]
进度：Makefile文件写好了，经测试amd64平台linux正常运行

**Comment by heky12356** [comment]
实现了用config保存端口，ws，以及群号的变量，使在实际使用中不用重复编译

**Comment by heky12356** [comment]
打包完成，已经发布v1.0release
https://github.com/heky12356/synctoqq/releases/tag/build

**Comment by StevenRCE0** [comment]
如果有兴趣可以 force push 到 [IOGAS-QQ](https://github.com/io-club/IOGAS-QQ)，稍后给你权限

**Comment by heky12356** [comment]
@StevenRCE0 直接覆盖掉吗

**Comment by StevenRCE0** [comment]
> @StevenRCE0 直接覆盖掉吗

嗯，旧代码我放到 `stale` 分支下了，直接覆盖掉 main 吧

**Comment by heky12356** [comment]
ok

**Comment by trdthg** [comment]
我就知道，你的代码必有问题

- git commit message 就是一坨
- 你怎么把 .github 和 .vscode 文件夹也搞上去了？

**Comment by trdthg** [comment]
记得创建个茶话会的报名 issue，第一次时间可以定在两-三周后？ 时间你可以自己定

- 创建完 issue
- 部署测试成功

后我会把这个 issue 关闭

**Comment by heky12356** [comment]
两个文件夹是测试的时候需要就留着了，等下重新传，commit确实是一坨，下次注意

**Comment by trdthg** [comment]
Good job
